### ISSUE TITLE
Tá, senta lá, Cláudia! #hacktoberfest

### ISSUE THREAD

**Issue by ocarneiro** [ocarneiro/para-entender-a-internet#12]
Quando ainda não era tão famosa assim, Xuxa apresentava um programa de TV meio caótico em que as crianças faziam o que queriam. Para colocar ordem na casa, em algum momento ela diz "Tá, senta lá, Cláudia" para uma menina que queria mandar um beijo para a mãe, pra família e pra você. Quem consegue encontrar esse vídeo?

**Comment by wesleyroh** [comment]
Bom dia, encontrei e ja adicionei no código, só aceitar lá.

**Comment by jtemporal** [comment]
fixed on #25
