### ISSUE TITLE
E o bambú? #hacktoberfest

### ISSUE THREAD

**Issue by ocarneiro** [ocarneiro/para-entender-a-internet#13]
Silvio Santos às vezes abria o programa para participação de pessoas da platéia. Uma vez uma menina pediu para contar uma piada e a piada era de baixo calão. Quem sabe do que estou falando pode fazer o pull request.

**Comment by sergiomario** [comment]
https://github.com/ocarneiro/para-entender-a-internet/pulls

**Comment by ocarneiro** [comment]
Closed by #14
