### ISSUE TITLE
Adicionar requisitos para Hacktoberfest

### ISSUE THREAD

**Issue by gabriel19913** [ocarneiro/para-entender-a-internet#299]
Boa tarde, não sei se foram informados, mas como esse repositório comumente recebe contribuições durante a hacktoberfest achei que seria interessante avisá-los.
Agora para um repositório valer para o Hacktoberfest ele deve ter "hacktoberfest" como tópico, além disso, as regras mudaram também para um PR ser aceito durante o evento, isso tudo foi dito [nesse update](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Comment by Gangorra** [comment]
Então este repositório não conta para o evento de 2021?

**Comment by dehatanes** [comment]
Infelizmente não @Gangorra 😞

**Comment by ocarneiro** [comment]
Opa! Vi aqui agora que estamos fora da festa. É só acrescentar o tópico? O link no primeiro comentário tá quebrado. Se tiverem outras orientações, avisem aqui que a gente providencia.

**Comment by ocarneiro** [comment]
Adicionei o tópico. Se pintarem outros requisitos, avisem por favor.
