### ISSUE TITLE
Cilada, Bino! #hacktoberfest

### ISSUE THREAD

**Issue by ocarneiro** [ocarneiro/para-entender-a-internet#8]
"Cilada, Bino" é um meme que veio da série Carga Pesada. Tem o Stênio Garcia e Antônio Fagundes. Como vazaram uns nudes do Stênio, seria interessante fazer uma referência à notícia. Favor não incluir nudes no pull request.

**Comment by Thaynannadu** [comment]
Adicionei esse! e fiz uma melhoria nas imagens, acho que gif cai melhor! Vou mandar o PR!

**Comment by jtemporal** [comment]
resolvido no #22
